# Generated by Django 4.1.2 on 2022-11-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_author_created_author_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='summary',
            field=models.TextField(help_text='Enter a brief summary of the author', max_length=1000, null=True),
        ),
    ]
