# Generated by Django 4.1.2 on 2022-11-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_author_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='copy_summary',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
